#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=`getApplication`

runApplication blockMesh
runApplication mapFields -sourceTime latestTime ../pitzDaily-simple
rm 0/epsilon 0/k 0/p
runApplication $application

# ----------------------------------------------------------------- end-of-file
